name: Automated Preprocessing

permissions:
  contents: write

on:
  push:
    paths:
      - '**. csv'

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Run a script
        run: echo "Triggered by commit ${{ github.sha }}"
 
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Automation Script
        run: python preprocessing/automate_Muhammad-Alif-Aditya.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add preprocessing/winequality_preprocessed.csv
          git commit -m "Update preprocessed data otomatis" || echo "Tidak ada perubahan"
          # set remote URL so push uses the token for authentication
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref_name }}